//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jupiter._24Crafts.Data.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CratfsDb : DbContext
    {
        public CratfsDb()
            : base("name=CratfsDb")
        {
        }

        static CratfsDb() {
            var _dependency = typeof(System.Data.Entity.SqlServer.SqlProviderServices);
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MainMenu> MainMenus { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User_Role_Tie> User_Role_Tie { get; set; }
        public virtual DbSet<MessageDeliveryConfiguration> MessageDeliveryConfigurations { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Opportunity> Opportunities { get; set; }
        public virtual DbSet<OpportunityConfiguration> OpportunityConfigurations { get; set; }
        public virtual DbSet<OpportunityResponse_User_Tie> OpportunityResponse_User_Tie { get; set; }
        public virtual DbSet<Profession> Professions { get; set; }
        public virtual DbSet<Profession_Opportunity_Tie> Profession_Opportunity_Tie { get; set; }
        public virtual DbSet<ProfileView> ProfileViews { get; set; }
        public virtual DbSet<Role_Menu_Tie> Role_Menu_Tie { get; set; }
        public virtual DbSet<SpamList> SpamLists { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<Language_User_Tie> Language_User_Tie { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<ExceptionLog> ExceptionLogs { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<OTP> OTPs { get; set; }
        public virtual DbSet<EmailOutbox> EmailOutboxes { get; set; }
        public virtual DbSet<BlockList> BlockLists { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Profession_User_Tie> Profession_User_Tie { get; set; }
        public virtual DbSet<AuditTrack> AuditTracks { get; set; }
        public virtual DbSet<ConsumerEvent> ConsumerEvents { get; set; }
        public virtual DbSet<Advertisement> Advertisements { get; set; }
    }
}
