//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jupiter._24Crafts.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpportunityResponse_User_Tie
    {
        public int ID { get; set; }
        public int OpportunityId { get; set; }
        public long UserId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Opportunity Opportunity { get; set; }
        public virtual User User { get; set; }
    }
}
