//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jupiter._24Crafts.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportunity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opportunity()
        {
            this.OpportunityResponse_User_Tie = new HashSet<OpportunityResponse_User_Tie>();
            this.Profession_Opportunity_Tie = new HashSet<Profession_Opportunity_Tie>();
        }
    
        public int OpportunityId { get; set; }
        public string Description { get; set; }
        public string Remuneration { get; set; }
        public long CreatedByUserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<long> IsApprovedBy { get; set; }
        public string IsApprovedComments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpportunityResponse_User_Tie> OpportunityResponse_User_Tie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profession_Opportunity_Tie> Profession_Opportunity_Tie { get; set; }
        public virtual User User { get; set; }
    }
}
