//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jupiter._24Crafts.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTP
    {
        public long OtpID { get; set; }
        public string MobileNum { get; set; }
        public string OTP1 { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
