//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jupiter._24Crafts.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Menu_Tie
    {
        public long ID { get; set; }
        public Nullable<long> RoleId { get; set; }
        public long MainMenuID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public long CreatedBy_UserID { get; set; }
        public Nullable<long> ModifiedBy_UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual MainMenu MainMenu { get; set; }
        public virtual Role Role { get; set; }
    }
}
