//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jupiter._24Crafts.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public string TokenKey { get; set; }
        public Nullable<System.DateTime> IssuedTime { get; set; }
        public Nullable<System.DateTime> ExpiredTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
