//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jupiter._24Crafts.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public long ID { get; set; }
        public long UserId { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string Hobbies { get; set; }
        public string SelfDescription { get; set; }
        public string Qualification { get; set; }
        public Nullable<int> ExpYear { get; set; }
        public Nullable<int> ExpMonth { get; set; }
        public string CurrAssignment { get; set; }
        public string LastAssignment { get; set; }
        public Nullable<System.DateTime> AvailabilityFrom { get; set; }
        public Nullable<System.DateTime> AvailabilityTo { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> PrimaryProfessionId { get; set; }
        public string GoogleDriveUrl { get; set; }
        public string YputubeChannel { get; set; }
        public string Remunaration { get; set; }
        public Nullable<int> CountryCode { get; set; }
    
        public virtual User User { get; set; }
    }
}
